= Tadman

Some Package Manager Written in Python

This is a (universal?) package manager that is currently in developement. It
is being designed to act as wrapper for basic commands like autotools and
CMake. It is written in pure python, and has very few dependencies.

== Dependencies

The necessary dependencies are:

* Python 3 (_obviously_)
* pygobject (for the GTK+ 3 interface)

Some optional dependencies are:

* CMake, to build CMake projects (You can find it 
https://cmake.org/[here])

== Installation

Tadman can be install using git and setuptools using the following commands
on a GNU/Linux system:

```
$ git clone https://github.com/KeepPositive/Tadman.git
$ cd Tadman
# python3 setup.py install
```

You should now have an executable named ``tadman`` in your path.

== Execution

Tadman should make building source code packages easier. Try it out by 
downloading some source code that uses autotools or CMake, and then run the
following:

```
$ python3 tadman_main.py [ARGUMENT] [PATH]
```

A GTK+ 3 GUI will open, where you can check off the options you want, or 
leave the ones you don't blank. Then make sure the proper program name and
version are set on the right via the text boxes. Once you are ready, hit 
run, and assuming you have all of the dependencies necessary, your program 
will be installed. 

For a complete list of availble arguments, check out
link:docs/tadman.man.adoc[the man page].
