= tadman(8)
Ted Moseley
v0.1.0
:manmanual: TADMAN
:mansource: TADMAN

== NAME

tadman - An intuitive symlink package manager written in Python

== SYNOPSIS

*tadman-curses* [ARGUMENT]

*tadman-gtk* [ARGUMENT]

== DESCRIPTION

Tadman is a portable package manager which can run on any GNU/Linux based
operating system. It is written in pure python3 and possesses very few
dependencies.

The idea is that Tadman acts as a wrapper for popular build systems. Currently,
Tadman is able to build GNU Autotools and CMake based projects. It then
installs the compiled sources in the '/usr/local/tadman' directory. Here,
packages are placed within their own folders. The contents of these folders
are then linked to the '/usr/bin' through a system of symlinks.

Similarly, Tadman can uninstall packages by removing all symlinks.

== ARGUMENTS

*build [PATH]* - Run the standard build and install process

*help* - Print this help message.

*install [NAME]* - Link files in a package's install directory to root

*uninstall [NAME]* - Unlink files from root folders

*version* - Print a version string

== EXAMPLES

=== Build

Let's say you want to install a program using Tadman named 'foo' and it is
version '1.2.3'. The folder containing the source code is likely named
'foo-1.2.3'. So we will build it and install it using this command:

``tadman-curses build /path/to/foo-1.2.3``

Simply follow the prompts, choose your options, and the build process will
begin.

=== Uninstall

Now, let's say that 'foo-1.2.4' is released a month later. You will want to
uninstall the 'foo-1.2.3' package. Just run this command:

``tadman-curses uninstall foo-1.2.3``

The symlinks hold the program in place will be broken, and you can now build
and install foo-1.2.4 just like we did previous.

=== Reinstall

As one last example, let's say there is a bug in 'foo-1.2.4', and you still
have foo-1.2.3 in your '/usr/local/tadman' directory. You can uninstall
'foo-1.2.4', and reinstall 'foo-1.2.3' using two commands:

``tadman-curses uninstall foo-1.2.4``

``tadman-curses install foo-1.2.3``

NOTE: All of these commands must be run as the root user. If you are not the
root user, Tadman will display an error message.

== COPYING

Copyright © 2016 Ted Moseley. Free use of this software is granted under
the terms of the MIT License

<https://opensource.org/licenses/MIT>.
